spring.application.name=chatBot

# Groq API (OpenAI compatible)
spring.ai.openai.api-key=yourkey(openai)
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=preferredmodel

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:bikedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA - auto creates tables from your Java classes
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Browser Console - so you can SEE your database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server port
server.port=8080

#setting data.sql
spring.jpa.defer-datasource-initialization=true
